  services:
  - type: web
    name: quest1-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db     # ← RenderのPostgreSQL名
          property: connectionString

