services:
  - type: web
    name: quest1-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: |
      flask db upgrade &&
      gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db  # ← RenderのPostgreSQL名と一致
          property: connectionString
