"""初期マイグレーション

Revision ID: 612ae2e89f67
Revises: 
Create Date: 2025-06-10 14:35:58.503991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612ae2e89f67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('run_50m', sa.Float(), nullable=True),
    sa.Column('base_running', sa.Float(), nullable=True),
    sa.Column('long_throw', sa.Float(), nullable=True),
    sa.Column('pitch_speed', sa.Float(), nullable=True),
    sa.Column('hit_speed', sa.Float(), nullable=True),
    sa.Column('swing_speed', sa.Float(), nullable=True),
    sa.Column('bench_press', sa.Float(), nullable=True),
    sa.Column('squat', sa.Float(), nullable=True),
    sa.Column('member_approval', sa.Boolean(), nullable=True),
    sa.Column('coach_approval', sa.Boolean(), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('user')
    # ### end Alembic commands ###
